// lib/blog-posts.ts

export const blogPosts = [
  {
    slug: "dutch-various-languages",
    title: "Learning Dutch from Various Languages: Pros, Cons, and What to Focus On",
    description: "If you're interested in learning Dutch, it's helpful to know how your native language or other languages you speak might...",
    date: "23-04-2024",
    image: "/images/blog-26.png",
  },
  {
    slug: "mvv-test",
    title: "All you need to know about the basic civic integration examination 'machtiging van voorlopig verblijf' or MVV test.",
    description: "1. What is the MVV test?If you come from a country outside of the EU and you want to join a partner or spouse in the Netherlands, you have to apply fo...",
    date: "24-05-2020",
    image: "/images/blog-25.jpg",
  },
  {
    slug: "ona-dutch-exam",
    title: "All you need to know about 'Oriëntatie op de Nederlandse arbeidsmarkt' or 'ONA' for the Dutch civic integration exam.",
    description: "1. Wat is Oriëntatie op de Nederlandse arbeidsmarkt?This part of the 'inburgeringsexamen' is all about employement in the Netherlands....",
    date: "24-05-2020",
    image: "/images/blog-24.jpg",
  },
  {
    slug: "kennis-nederlandse-maatschappij",
    title: "All you need to know about the part ‘ Kennis van de Nederlandse maatschappij' or KNM of the Dutch civic integration exam or inburgeringsexamen.",
    description: "1. What does 'kennis van de Nederlandse maatschappij' mean?In order to be approved for Dutch citizenship or permanent residence,...",
    date: "24-05-2020",
    image: "/images/blog-23.jpeg",
  },
  {
    slug: "speaking-dutch-inburgeringsexamen",
    title: "All you need to know about the Speaking (spreekvaardigheid) part of the inburgeringsexamen.",
    description: "Speaking at B1 level in Dutch means you can have a day to day conversation or a simple discussion where you can voice your opinion....",
    date: "19-05-2020",
    image: "/images/blog-22.jpg",
  },
  {
    slug: "writing-dutch-inburgeringsexamen",
    title: "All you need to know about the writing or 'schrijven' part of the inburgeringsexamen",
    description: "1. What does writing at B1 level mean? To write at B1 level in Dutch you have to be able to write text usefull in daily interactions both publicly...",
    date: "19-05-2020",
    image: "/images/blog-21.jpg",
  },
  {
    slug: "listening-dutch-inburgeringsexamen",
    title: "All you need to know about the Listening or 'luisteren' part of the Dutch civic integration exam-het inburgeringsexamen.",
    description: "1. What does listening at B1 level mean?Similar as with the reading part, at B1 level you need to generally understand short audio clips and...",
    date: "19-05-2020",
    image: "/images/blog-20.jpg",
  },
  {
    slug: "speak-dutch-fluently",
    title: "5 steps to speak Dutch fluently",
    description: "When learning Dutch it is important, especially at the beginning, to focus on input, on listening and reading. However,...",
    date: "18-03-2020",
    image: "/images/blog-19.jpg",
  },
  {
    slug: "reading-dutch-inburgeringsexamen",
    title: "All you need to know about the Reading, or 'lezen', part of the Inburgeringsexamen.'",
    description: "Since you are reading this post, you are considdering, or preparing, to take the Dutch civic integration exam. In this blog we give you more practical information about the...",
    date: "19-05-2020",
    image: "/images/blog-18.jpg",
  },
  {
    slug: "about-dutch-inburgeringsexamen",
    title: "All you need to know about the Dutch civic integration exam, also referred to as 'inburgeringsexamen'",
    description: "For many people relocating to the Netherlands and the maze of procedures and 'how-to's', when doing so, prove to be quite a headache. We provide advice an...",
    date: "19-05-2020",
    image: "/images/blog-17.jpeg",
  },
  {
    slug: "funny-dutch-word",
    title: "Where does the funny Dutch word ‘de neushoorn’ come from?",
    description: "The word neushoorn can be split into two separate words, de neus and the hoorn. Both words can have different meanings in Dutch:...",
    date: "02-07-2020",
    image: "/images/blog-16.jpeg",
  },
  {
    slug: "akv-test-part-c",
    title: "All you need to know about AKV test part C : English reading skills",
    description: "As discussed in our previous blogs, the AKV test consists of 5 separate exam parts....",
    date: "21-01-2020",
    image: "/images/blog-15.jpg",
  },
  {
    slug: "akv-test-part-a",
    title: "All you need to know about AKV test part A: summary and presentation",
    description: "As mentioned in our previous blog, the following professions when coming from outside the EU, need to register with BIG in order to practice i...",
    date: "08-01-2020",
    image: "/images/blog-14.png",
  },
  {
    slug: "akv-test-part-d",
    title: "All you need to know about the AKV – Test part D: Knowledge of the Dutch healthcare",
    description: "The AKV test consists of 5 separate exam parts. In our previous blogs we discussed the first 3 pats of the test namely part A, part B & part C. ...",
    date: "13-01-2020",
    image: "/images/blog-13.jpeg",
  },
  {
    slug: "akv-test-part-b",
    title: "All you need to know about AKV test part B: consultation and report",
    description: "So far we have discussed the first two aspects of the AKV process. First was the registration process and second was the first part of the actual...",
    date: "13-01-2020",
    image: "/images/blog-12.jpg",
  },
  {
    slug: "4-questions-sinterklaas",
    title: "4 questions Dutch children ask about Sinterklaas (and possible answers from their parents)",
    description: "So we know that Sinterklaas is a celebration mainly for the children and from 3 weeks prior all the kids can put out their shoes, visit the Sint at the town square and sing a lot of song...",
    date: "05-12-2019",
    image: "/images/blog-11.jpg",
  },
  {
    slug: "information-doctors",
    title: "Information for doctors, pharmacists, dentists and psychologists from outside the EEA that want to work in the Netherlands.",
    description: "For many professionals relocating to Europe the maze of procedures and 'how-to's' prove to be quite a headache. We have been asked many...",
    date: "08-01-2020",
    image: "/images/blog-10.jpg",
  },
  {
    slug: "visit-scheveningen",
    title: "5 reasons why you need to visit Scheveningen on New Years Eve.",
    description: "Although The Netherlands is a small country it has an impressively long coastline, for its size, extending for more than 500 km along the Norther...",
    date: "12-12-2019",
    image: "/images/blog-9.jpeg",
  },
  {
    slug: "dutch-irregular-verbs",
    title: "How to remember the Dutch irregular verbs in the past tense",
    description: "Just like in many languages there are irregular and defective verbs in Dutch. Although there are only six completely irregular verbs in the...",
    date: "28-11-2019",
    image: "/images/blog-8.jpg",
  },
  {
    slug: "the-dutch-surprise",
    title: "All you need to know about the Dutch 'surprise'.",
    description: "As always, during the first days of December, everyone in The Netherlands celebrates the Saint Nicolas or Sinterklaas festival...",
    date: "04-12-2019",
    image: "/images/blog-7.jpg",
  },
  {
    slug: "feast-of-sinterklaas",
    title: "5 things to know about the Dutch and Flemish feast of Sinterklaas (Saint- Nicholas)",
    description: "The Sinterklaas festival is celebrated in Belgium and The Netherlands on the 5th and 6th of December every year. During this period, children put...",
    date: "27-11-2019",
    image: "/images/blog-6.jpg",
  },
  {
    slug: "7-dutch-sinterklaas-accessories",
    title: "7 Dutch Sinterklaas accessories explained",
    description: "Sinterklaas, also known as Saint Nicholas, is a Dutch character loved by children and adults alike and shouldn't be confused with Father...",
    date: "25-11-2019",
    image: "/images/blog-5.jpg",
  },
  {
    slug: "5-christmas-markets",
    title: "5 Christmas markets in the Netherlands recommended by Learn-Dutch-Online",
    description: "The temperature starts to drop, the heating turns on,and the days get shorter, as the Dutch winter settles in. It is dark and cold outside making...",
    date: "24-11-2019",
    image: "/images/blog-4.jpg",
  },
  {
    slug: "5-places-belgium",
    title: "5 Places in Belgium to visit around Christmas time",
    description: "Everyone knows the best places to visit around Christmas in their own city and region, but maybe it's time for a little portion of jingle bells elsewhere?...",
    date: "24-11-2019",
    image: "/images/blog-3.jpg",
  },
  {
    slug: "feest-sint-maarten",
    title: "4 things to know about the Dutch and Flemish feast of St. Martin (Sint-Maarten)",
    description: "Saint Martin of Tours was a Roman soldier who was baptised as an adult and became a bishop in a French town. The most famous legend...",
    date: "07-11-2019",
    image: "/images/blog-2.jpg",
  },
  {
    slug: "6-reasons-to-visit-ypres",
    title: "6 reasons to visit YPRES (Ieper) on the 11th of November.",
    description: "The 11th of November is the day of Armistice in Belgium. Ypres, situated in West-Flanders (West-Vlaanderen) also called the Westhoek, is...",
    date: "05-11-2019",
    image: "/images/blog-1.jpg",
  },
];
